import type { ApplicantInfo, DiscordConfig, ResearchResult } from './types';

/**
 * Sends the generated report (as a PDF attachment) plus applicant + research
 * metadata to a Discord channel via the Discord Bot API.
 */
export async function sendReportToDiscord(
  config: DiscordConfig,
  applicant: ApplicantInfo,
  result: ResearchResult,
  pdfBuffer: Buffer,
  filename: string
): Promise<void> {
  const { botToken, channelId } = config;
  if (!botToken || !channelId) {
    throw new Error('Discord Bot Token and Channel ID are required.');
  }

  const embed = {
    title: `📊 New Research Report: ${result.company.name}`,
    color: 0x3a9884,
    fields: [
      { name: 'Applicant Name', value: applicant.name || 'N/A', inline: true },
      { name: 'Applicant Email', value: applicant.email || 'N/A', inline: true },
      { name: 'Company Name', value: result.company.name || 'N/A', inline: false },
      { name: 'Company Website', value: result.company.website || 'N/A', inline: false },
    ],
    timestamp: new Date().toISOString(),
  };

  const form = new FormData();
  form.append(
    'payload_json',
    JSON.stringify({
      content: `New company research report generated by **${applicant.name || 'a user'}**.`,
      embeds: [embed],
    })
  );
  form.append('files[0]', new Blob([pdfBuffer], { type: 'application/pdf' }), filename);

  const res = await fetch(`https://discord.com/api/v10/channels/${channelId}/messages`, {
    method: 'POST',
    headers: {
      Authorization: `Bot ${botToken}`,
    },
    body: form,
  });

  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`Discord API request failed (${res.status}): ${text.slice(0, 300)}`);
  }
}
