import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToBuffer, Link } from '@react-pdf/renderer';
import type { ResearchResult } from './types';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
    color: '#1a1a1a',
  },
  headerBar: {
    borderBottom: '2 solid #3a9884',
    paddingBottom: 12,
    marginBottom: 20,
  },
  brand: {
    fontSize: 10,
    color: '#3a9884',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  companyName: {
    fontSize: 24,
    fontWeight: 700,
    marginBottom: 2,
  },
  website: {
    fontSize: 11,
    color: '#3a9884',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 700,
    marginTop: 18,
    marginBottom: 8,
    color: '#17171c',
    borderBottom: '0.5 solid #cccccc',
    paddingBottom: 4,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  label: {
    width: 90,
    fontWeight: 700,
    color: '#555555',
  },
  value: {
    flex: 1,
  },
  paragraph: {
    lineHeight: 1.5,
    marginBottom: 8,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  bullet: {
    width: 12,
  },
  bulletText: {
    flex: 1,
    lineHeight: 1.4,
  },
  competitorCard: {
    borderLeft: '2 solid #3a9884',
    paddingLeft: 10,
    marginBottom: 10,
  },
  competitorName: {
    fontSize: 12,
    fontWeight: 700,
  },
  competitorWebsite: {
    fontSize: 10,
    color: '#3a9884',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#999999',
    textAlign: 'center',
    borderTop: '0.5 solid #dddddd',
    paddingTop: 8,
  },
});

function ReportDocument({ result }: { result: ResearchResult }) {
  const { company, competitors, generatedAt } = result;
  return (
    <Document title={`${company.name} - Company Research Report`}>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBar}>
          <Text style={styles.brand}>Company Research Report</Text>
          <Text style={styles.companyName}>{company.name}</Text>
          <Link src={company.website} style={styles.website}>
            {company.website}
          </Link>
        </View>

        <Text style={styles.sectionTitle}>Company Information</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Website</Text>
          <Text style={styles.value}>{company.website || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Phone</Text>
          <Text style={styles.value}>{company.phone || 'Not publicly available'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Address</Text>
          <Text style={styles.value}>{company.address || 'Not publicly available'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Industry</Text>
          <Text style={styles.value}>{company.industry || 'Unknown'}</Text>
        </View>

        <Text style={styles.sectionTitle}>Summary</Text>
        <Text style={styles.paragraph}>{company.summary}</Text>

        <Text style={styles.sectionTitle}>Products / Services</Text>
        {company.productsServices.length === 0 && (
          <Text style={styles.paragraph}>No products or services identified.</Text>
        )}
        {company.productsServices.map((item, i) => (
          <View style={styles.bulletRow} key={`ps-${i}`}>
            <Text style={styles.bullet}>•</Text>
            <Text style={styles.bulletText}>{item}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>AI-Generated Pain Points</Text>
        {company.painPoints.length === 0 && (
          <Text style={styles.paragraph}>No pain points identified.</Text>
        )}
        {company.painPoints.map((item, i) => (
          <View style={styles.bulletRow} key={`pp-${i}`}>
            <Text style={styles.bullet}>•</Text>
            <Text style={styles.bulletText}>{item}</Text>
          </View>
        ))}

        <Text style={styles.sectionTitle}>Competitor Analysis</Text>
        {competitors.length === 0 && (
          <Text style={styles.paragraph}>No competitors identified.</Text>
        )}
        {competitors.map((c, i) => (
          <View style={styles.competitorCard} key={`comp-${i}`}>
            <Text style={styles.competitorName}>{c.name}</Text>
            {c.website ? (
              <Link src={c.website} style={styles.competitorWebsite}>
                {c.website}
              </Link>
            ) : (
              <Text style={styles.competitorWebsite}>Website not found</Text>
            )}
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by Company Research Assistant on {new Date(generatedAt).toLocaleString()} •
          Data sourced from public web content and AI analysis; verify before outreach.
        </Text>
      </Page>
    </Document>
  );
}

export async function generateReportPdf(result: ResearchResult): Promise<Buffer> {
  return renderToBuffer(<ReportDocument result={result} />);
}
